In [17]:
prices = [100, 102, 101, 105]

print(prices[0])   # first value
print(prices[-1])
print(prices[:3])  # slice from index 1 to 2

100
105
[100, 102, 101]

In [18]:
stock = {
    "name": "RELIANCE",
    "price": 2500,
    "volume": 100000
}

print(stock["name"])
print(stock["price"])
print(stock["volume"])

RELIANCE
2500
100000

In [19]:
def average_price(prices):
    return sum(prices) / len(prices)

def calculation(a,b,c,d):
    return a + b - c * d

print(average_price([100, 102, 101]))
print(calculation(10, 5, 2, 3))

101.0
9

In [20]:
# using pandas for exporting the data to csv file
import pandas as pd

df = pd.read_csv("../data/sample_stock.csv")

df

         Date  Open  High  Low  Close  Volume
0  2024-01-01   100   105   98    102  100000
1  2024-01-02   102   108  101    107  120000
2  2024-01-03   107   109  104    105   90000
3  2024-01-04   105   110  103    109  150000
4  2024-01-05   109   112  107    111  130000
5  2024-01-06   111   115  110    114  140000
6  2024-01-07   114   118  113    117  160000
7  2024-01-08   117   119  115    116  110000
8  2024-01-09   116   120  114    119  170000
9  2024-01-10   119   122  118    121  180000

In [21]:
df.head()

         Date  Open  High  Low  Close  Volume
0  2024-01-01   100   105   98    102  100000
1  2024-01-02   102   108  101    107  120000
2  2024-01-03   107   109  104    105   90000
3  2024-01-04   105   110  103    109  150000
4  2024-01-05   109   112  107    111  130000

In [24]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [ ]:
df["Volume"]

0    1000
1    1200
2     900
3    1500
Name: Volume, dtype: int64

In [ ]:
#finding the double of  avg price
avg_price = df["Price"].mean()*2
print(avg_price)

204.0

In [ ]:
# finding the mac price 
max_price = df["Price"].max()
print(max_price)

105